---
- name: Set node availability
  community.docker.docker_node:
    hostname: "{{ ansible_hostname }}"
    availability: "{{ docker__swarm_node_availability }}"
  delegate_to: "{{ groups['docker__swarm_managers'][0] }}"
  run_once: True

- name: Check for running containers
  community.docker.docker_host_info:
    containers: True
  register: docker__container_info
  until: docker__container_info.containers | length == 0 #TODO I will probably have to adjust this according to the return of the module
  retries: 5
  delay: 10
  when: docker__swarm_node_availability == 'drain'

- name: Debug container information
  debug:
    msg: "Running containers: {{ docker__container_info.containers }}"
  when: docker__swarm_node_availability == 'drain'

- name: Register fact about running containers
  set_fact:
    docker__running_containers: "{{ container_info.containers | length == 0 }}"
  when: docker__swarm_node_availability == 'drain'
